API+WEBSITE/UMS/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using UMS.DbContexts;
using UMS.Models;

namespace UMS.Controllers
{
    public class StudentController : Controller
    {
        private readonly ProjectDbContext _context;
        private readonly int _minAge = 16;

        public StudentController(ProjectDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            SetUserId();
            var dataList = await _context.Students.Include(s => s.Subject).ToListAsync();
            return View(dataList);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            SetUserId();

            if (id == null) return NotFound();
            var student = await _context.Students.Include(s => s.Subject).FirstOrDefaultAsync(m => m.Id == id);
            if (student == null) return NotFound();

            return View(student);
        }

        public IActionResult Create()
        {
            SetUserId();
            GetSubjectsSli();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Student student)
        {
            SetUserId();
            GetSubjectsSli(student);
            if (!ModelState.IsValid) return View(student);
            var age = (DateTime.Today - student.Dob.Date).TotalDays / 365;
            if (_minAge > age)
            {
                ViewBag.ErrorMsg = "Sorry! Age Must be At least 16+ Years!";
                return View(student);

            }
            var isEmailExists = (await _context.Students.FirstOrDefaultAsync(c => c.Email.ToLower().Equals(student.Email.Trim().ToLower()))) != null;
            if (isEmailExists)
            {
                ViewBag.ErrorMsg = $"Sorry! This Email [{student.Email}] Already Exists!";
                return View(student);
            }


            student.Id = Guid.NewGuid();
            _context.Add(student);
            var isAdded = await _context.SaveChangesAsync() > 0;
            if (isAdded && HttpContext.Session.GetString("UserId") != null)
            {
                return RedirectToAction(nameof(Index));
            }
            if (isAdded)
            {
                return RedirectToAction(nameof(Details), new { id = student.Id });
            }

            return View(student);

        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            SetUserId();
            if (id == null) return NotFound();
            var student = await _context.Students.FindAsync(id);
            if (student == null) return NotFound();
            GetSubjectsSli(student);
            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Student student)
        {
            SetUserId();
            if (id != student.Id) return NotFound();
            var age = (DateTime.Today - student.Dob.Date).TotalDays / 365;
            if (_minAge > age)
            {
                ViewBag.ErrorMsg = "Sorry! Age Must be At least 16+ Years!";
                return View(student);

            }

            var isEmailExists = (await _context.Students.FirstOrDefaultAsync(c => c.Email.ToLower().Equals(student.Email.Trim().ToLower()) && c.Id != student.Id)) != null;
            if (isEmailExists)
            {
                ViewBag.ErrorMsg = $"Sorry! This Email [{student.Email}] Already Exists!";
                return View(student);
            }


            GetSubjectsSli(student);
            if (!ModelState.IsValid) return View(student);
            _context.Update(student);
            var isUpdated = await _context.SaveChangesAsync() > 0;
            if (isUpdated) return RedirectToAction(nameof(Index));

            return View(student);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            SetUserId();
            if (id == null) return NotFound();
            var student = await _context.Students.Include(s => s.Subject).FirstOrDefaultAsync(m => m.Id == id);
            if (student == null) return NotFound();

            return View(student);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            SetUserId();
            var student = await _context.Students.FindAsync(id);
            if (student != null) _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private void GetSubjectsSli(Student student = null)
        {
            student ??= new Student();
            ViewBag.SubjectId = new SelectList(_context.Subjects, "Id", "Name", student.SubjectId);
        }

        private void SetUserId() => ViewBag.UserId = HttpContext.Session.GetString("UserId");
    }
}

API+WEBSITE/UMS/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using UMS.DbContexts;
using UMS.Models;

namespace UMS.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ProjectDbContext _context;

        public SubjectController(ProjectDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            SetUserId();
            var dataList = await _context.Subjects.ToListAsync();
            return View(dataList);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null) return NotFound();
            var subject = await _context.Subjects.FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null) return NotFound();
            SetUserId();

            return View(subject);
        }

        public IActionResult Create()
        {
            SetUserId();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Subject subject)
        {
            SetUserId();
            if (!ModelState.IsValid) throw new Exception("Sorry! There Some Error in Form Validation!");
            var isExists = (await _context.Subjects.FirstOrDefaultAsync(c => c.Name.ToLower().Equals(subject.Name.Trim().ToLower()))) != null;
            if (isExists)
            {
                ViewBag.ErrorMsg = $"Sorry! This Subject [{subject.Name}] Already Exists!";
                return View(subject);
            }

            subject.Id = Guid.NewGuid();
            _context.Add(subject);
            var isAdded = await _context.SaveChangesAsync() > 0;
            if (isAdded) return RedirectToAction(nameof(Index));
            return View(subject);

        }


        public async Task<IActionResult> Edit(Guid? id)
        {
            SetUserId();
            if (id == null) return NotFound();
            var subject = await _context.Subjects.FindAsync(id);
            if (subject == null) return NotFound();
            return View(subject);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description")] Subject subject)
        {
            SetUserId();
            if (id != subject.Id) return NotFound();

            var isExists = (await _context.Subjects.FirstOrDefaultAsync(c => c.Name.ToLower().Equals(subject.Name.Trim().ToLower()) && c.Id != subject.Id)) != null;
            if (isExists)
            {
                ViewBag.ErrorMsg = $"Sorry! This Subject [{subject.Name}] Already Exists!";
                return View(subject);
            }

            if (ModelState.IsValid)
            {
                _context.Update(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(subject);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            SetUserId();
            if (id == null) return NotFound();
            var subject = await _context.Subjects.FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null) return NotFound();
            return View(subject);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            SetUserId();
            var subject = await _context.Subjects.FindAsync(id);
            if (subject != null)
            {
                _context.Subjects.Remove(subject);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(Guid id)
        {
            return _context.Subjects.Any(e => e.Id == id);
        }

        private void SetUserId() => ViewBag.UserId = HttpContext.Session.GetString("UserId");

    }
}

API+WEBSITE/UMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UMS.styles.css" asp-append-version="true" />

</head>
<body>
    <header style="background-color:navy">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" style="color:white" asp-area="" asp-controller="Home" asp-action="Index"> <img style="max-height:40px;max-width:40px;" src="~/imgs/logo.png" /></a>
                <h3>University of South Wales</h3>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color:white" asp-area="" asp-controller="Student" asp-action="Create">Student Reg.</a>
                        </li>

                        @if (ViewBag.UserId == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" style="color:white" asp-area="" asp-controller="Home" asp-action="Login">Admin-Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item"> <a class="nav-link text-color-white" style="color:white" asp-area="" asp-controller="Student" asp-action="Index">Student-List</a> </li>
                            <li class="nav-item"> <a class="nav-link text-color-white" style="color:white" asp-area="" asp-controller="Subject" asp-action="Index">Subject-List</a> </li>
                            <li class="nav-item"> <a class="nav-link text-color-white" style="color:white" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a> </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - <a asp-area="" asp-controller="Home" asp-action="Index">UMS</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>